nume = str(input("numele teau este = "))
print(f"Salut {nume}")
a = float(input("a = "))
b = float(input("b = "))
print(f"suma = {a+b}")
print(f"diferenta = {a-b}")
print(f"produsul = {a*b}")
l = float(input("l = "))
L = float(input("L = "))
print(f"aria = {l*L}")
print(f"primetru = {l*L*2}")
raza = float(input("raza = "))
print(f"aria cerc = {raza*raza*3.14}")
varsta = int(input("varsta ta = "))
print(f"teai nascut in {2026-varsta}")
celsius = int(input("grade C = "))
print(f"Farenhite ={(celsius * 1.8) + 32}")
cant = float(input("cant = "))
pret = float(input("pret = "))
print(f"suma finala {cant* pret}")
nota1 = float(input("nota1 = "))
nota2 = float(input("nota2 = "))
nota3 = float(input("nota3 = "))
print(f"media este {(nota1 + nota2 + nota3) / 2}")